### ISSUE TITLE
feature-request: Add the option to add the label as a Grouping meta tag.

### ISSUE THREAD

**Issue by thibmaek** [Evolution0/bandcamp-dl#103]
I've been relying heavily on this in spotify-ripper so I can order my collection per music label by adding it to the grouping tag in iTunes. Spotify-ripper also uses mutagen so this shouldn't be too big of an issue adding in I think when it comes to code. Would like to submit a PR, but have to look into this Python code first :D

**Comment by Evolution0** [comment]
Seems the label information isn't part of the JS we scrape though I roughly know where to find it.

Its shoved in a blob of data that I was probably going to add to BandcampJSON at some point anyway.

Once I do that its just a matter of throwing in the label metadata along with the rest of the data we currently use and using TIT1 to set the contentgroup (Group) tag. At least in theory, I have no idea how iTunes works or does its tags but from what a bit of research tells me I've got the right idea.

**Comment by Evolution0** [comment]
Update: Refactored BandcampJSON to return a list of JSON strings instead of creating multiple instances and returning individual strings. In the process of that added a separate function to retrieve the pagedata json string containing things like the label, other album names, etc

Edit: And done, grouping tag is added properly when the `--group` option is now used, granted I haven't tested on many albums yet but I added a check so that if the option is used and no label is found it simply does nothing.

As an aside the track date is no longer DDMM but Year.

Changes pushed, new release here and on PyPI with the changes, `pip install --upgrade bandcamp-downloader` to update.

**Comment by thibmaek** [comment]
Super!
