### ISSUE TITLE
Download with Southeast Asian characters fails

### ISSUE THREAD

**Issue by FireStarW** [Evolution0/bandcamp-dl#104]
**Python version:**  
Python 3.5.2+
**Bandcamp-dl version:**
bandcamp-dl 0.0.7-09
**Bancamp-dl options:**  
`bandcamp-dl https://chibitech.bandcamp.com/album/moenes-vol-1-the-idol-composers-groove --template=%{title}  --base-dir=/media/VR32/Sounds\ and\ music/Chiptunes/chibi-tech\ -\ MoeNES\ vol​\ ​1\ the\ idol\ composer\'s\ groove/`
**url:**  
https://chibitech.bandcamp.com/album/moenes-vol-1-the-idol-composers-groove
**options:**  

**Describe the issue:**
```

(1/10) [==================================================] :: Encoding: お兄ちゃんだからいいよ~'lyrics'
Downloading failed..
```

Either bandcamp-dl or mutagen doesn't like the characters used in the first tracks title

-------------------------

PEBKAC, deleting not.finished fixed it?

**Comment by Evolution0** [comment]
Strange, not.finished only stores the arguments used to execute bandcamp-dl in the event that it is interrupted in some way so that on next execution it can resume.

For the download failed message to be triggered while encoding would suggest that it detected the file already existing and attempted to jump straight to encoding.. I'm reopening this to remind myself to try the same command later and attempt to replicate this.

**Comment by FireStarW** [comment]
For clarification, the .tmp mp3 for this 1st track was still in the folder as well, from the first time this failed. There's a chance it may have been leftovers from an older version of bandcamp-dl as I had first ran this command, and then upgraded after having the issue the first time.

**Comment by Evolution0** [comment]
Indeed, if it was made with an older version that had encoding issues deleting it and rerunning bandcamp-dl would have fixed it.
