### ISSUE TITLE
Not all Dependencies Listed in Readme

### ISSUE THREAD

**Issue by ibrokemypie** [Evolution0/bandcamp-dl#108]
Not all of the requirements are included in the readme, which left me stumped for a while when it did not work after building, due to missing chardet.

**Comment by Evolution0** [comment]
They are optional requirements for those using a Python version below 3.6 which is why they are not in the readme but still included in the requirements.txt. They are used to monkey patch a bug in Requests with Python versions under 3.6.

And as they are included in the requirments.txt you should not have missed them at all, as that is what is universally used to install requirements.

But besides that there are prebuilt wheels after every update, so the repo is almost always equal to the current release binary, no need to build at all unless making changes to the code :)

**Comment by ibrokemypie** [comment]
This issue came up with Python 3.6.1
Came up while putting together a homebrew formula, which requires each dep to be re-stated as resources individually, since they hate formulas doing their own dependency resolution as with pip or setup.py over there.

**Comment by Evolution0** [comment]
This sounds more like an issue with Homebrew's restrictive policy on dependencies and less like an issue with bandcamp-dl itself.

**Comment by ibrokemypie** [comment]
The reasoning behind it is 
> [Because that circumvents our hash-checks, makes finding/fixing bugs harder, often breaks patches and disables the caching.](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md#we-dont-like-install-scripts-that-download-things)
  
Basically, not really an issue, but would be nice to list all dependencies when making a list of dependencies, as well as optional ones if possible.
