### ISSUE TITLE
No connection adapters were found

### ISSUE THREAD

**Issue by ksh-b** [Evolution0/bandcamp-dl#135]
**Python version:**  
Python 3.6.2 (default, Sep 16 2017, 23:57:30)
[GCC 4.2.1 Compatible Android Clang 5.0.300080 ] on linux

**Bandcamp-dl version:**
Bandcamp-dl 0.0.8-07

**Bancamp-dl options:**  
-d --base-dir 

**url:**  
https://trash80.bandcamp.com/releases

**options:**  
/sdcard/bandcamp

**Describe the issue:**
No connection adapters were found for 'http:https://t4.bcbits.com/stream/b29f8b78f26a036fa0aed519d5ae2508/mp3-128/1269638986?p=0&ts=1506589738&t=d15ceedfab961fd6e7fa3e4ef605fd538b414fcc&token=1506589738_2647a7a50c5f6dbe6c1f3a14093e699686676a55'
Downloading failed..

-------------------------

It was working fine the first time I tried this link. But I aborted before the first file could download (wanted to change directory). Thereafter, faced this issue.

**Comment by Evolution0** [comment]
Makes sense, if you take a look at the url it now has `http:https://` at the beginning of it which is invalid. I'm guessing the original error message was `Invalid Schema`.

Must be due to this bit:
```
    if 'mp3-128' in track['file']:
        track_metadata['url'] = "http:" + track['file']['mp3-128']
```

Which means either the file urls now include the http: bit in them or just in specific instances, does this happen on any other pages?

Edit: Seems like it might be a sitewide change, getting ready to push 0.0.8-08 which fixes it (and a previous not.finished file issue)

**Comment by Evolution0** [comment]
New release pushed, just `pip install --upgrade bandcamp-downloader`
