### ISSUE TITLE
can't run bandcamp-dl 

### ISSUE THREAD

**Issue by silkyclouds** [Evolution0/bandcamp-dl#152]
**Python version:**  

Python 3.6.5

**Bandcamp-dl version:**

**Bancamp-dl options:**  

**url:**  

**options:**  

**Describe the issue:**
can't run bandcamp-dl. getting this error : 

Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 7, in <module>
    from bandcamp_dl.bandcamp_dl import main
ModuleNotFoundError: No module named 'bandcamp_dl'

any clue what I can do to fix this ?

**Comment by Evolution0** [comment]
Strange, this is the first time such an error has come up anywhere other than when attempting to execute bandcamp_dl.py directly. Has it worked before this?

**Comment by silkyclouds** [comment]
Well I just installed bandcamp-dl using the procedure you’ve published. Then I can type bandamp-dl in my shell, and do get that error. :(

**Comment by silkyclouds** [comment]
Successfully installed bandcamp-downloader-0.0.8.post12 beautifulsoup4-4.6.3 certifi-2018.8.24 chardet-3.0.4 demjson-2.2.4 docopt-0.6.2 idna-2.7 mock-2.0.0 mutagen-1.41.1 pbr-4.2.0 requests-2.19.1 six-1.11.0 unicode-slugify-0.1.3 unidecode-1.0.22 urllib3-1.23

after what I run "bandcamp-dl" and get this : 

Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 7, in <module>
    from bandcamp_dl.bandcamp_dl import main
ModuleNotFoundError: No module named 'bandcamp_dl.bandcamp_dl'

**Comment by mrjovanovic** [comment]
I came across a similar issue. Did you by any chance install it with `pip install bandcamp-downloader`? This installs it with python 2 pip. On a Debian system, you need to install `python3-pip`, and then install bandcamp-dl with `pip3 install bandcamp-downloader`. Maybe try that?

(@iheanyi might be a good idea to add that bit to README.md)

**Comment by Evolution0** [comment]
Id be interested to know if `pip3 install` works in this case.. though its been some time since this issue was posted so I don't really expect an answer.

I'll wait a while then close this as I go through my backlog bit by bit.

**Comment by Jzbonner** [comment]
I actually encountered this issue trying to get bandcamp-dl working on Elementary OS (built on Linux Ubuntu 18.04 LTS). Bandcamp-dl won't run in a Python 2.7 environment, so in order to avoid this error: 

Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 7, in <module>
    from bandcamp_dl.bandcamp_dl import main
  File "/home/jarrett/.local/lib/python2.7/site-packages/bandcamp_dl/bandcamp_dl.py", line 49, in <module>
    from .bandcamp import Bandcamp
  File "/home/jarrett/.local/lib/python2.7/site-packages/bandcamp_dl/bandcamp.py", line 10
    def parse(self, url: str, art: bool=True) -> dict or None:
                       ^
SyntaxError: invalid syntax

...you have to either set your default python environment to Python3 or set up a virtual environment with Python3. Setting your default python environment to Python3 can cause issues if you use Python2 for literally anything else. So set up a virtual environment and get to downloading. 

Commands to Run for Linux/Ubuntu Distros: 
1. 'sudo apt-get install python3-venv'
2. 'cd' into your project directory 
3. 'python3 -m venv [name_of_your_project]' (i.e. python3 -m venv bandcamp_downloads) 
4. 'source /[name_of_your_project]/bin/activate' (i.e. source /bandcamp_downloads/bin/activate) 
5. Check for the python3 version by running 'python --version' should return a Python 3.X.X variant 
6. Install bandcamp downloader 'pip3 install bandcamp-downloader' 
7. Check bandcamp downloader version 'bandcamp-dl --version'
