### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'string'

### ISSUE THREAD

**Issue by jonnyburnaway** [Evolution0/bandcamp-dl#178]
**Python version:**  3.6.9

**Bandcamp-dl version:** bandcamp_downloader-0.0.9.post1

**Bancamp-dl options:**  bandcamp-dl URL

**Describe the issue:**
-------------------------

Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    load_entry_point('bandcamp-downloader==0.0.9.post1', 'console_scripts', 'bandcamp-dl')()
  File "/usr/local/lib/python3.6/dist-packages/bandcamp_downloader-0.0.9.post1-py3.6.egg/bandcamp_dl/__main__.py", line 92, in main
  File "/usr/local/lib/python3.6/dist-packages/bandcamp_downloader-0.0.9.post1-py3.6.egg/bandcamp_dl/bandcamp.py", line 40, in parse
  File "/usr/local/lib/python3.6/dist-packages/bandcamp_downloader-0.0.9.post1-py3.6.egg/bandcamp_dl/bandcampjson.py", line 18, in generate
  File "/usr/local/lib/python3.6/dist-packages/bandcamp_downloader-0.0.9.post1-py3.6.egg/bandcamp_dl/bandcampjson.py", line 29, in get_js
AttributeError: 'NoneType' object has no attribute 'string'

I've tried uninstallng and reinstalling from source, as [here](https://github.com/iheanyi/bandcamp-dl/issues/176#issuecomment-725842609) . 
I've also tried [this edit](https://github.com/iheanyi/bandcamp-dl/issues/173#issuecomment-706486250)  to bandcampjson.py, which worked for me last time. 

Unfortunately I think something's changed on the Bandcamp end...apologies but I'm not proficient enough to take it further...

**Comment by Evolution0** [comment]
I've been working on bandcamp-dl today and haven't noticed anything being different with Bandcamp itself that would break it, all my tests so far work.

This specific error usually comes up when it can't find the script on the page that contains the info it needs. This is something that happens when Bandcamp changes where the script is in some way but seeing as my other tests work this is highly unlikely.

And as the edit you mentioned is already integrated into the current version of the code I'm skeptical as to if you have the latest version of it at all.

Regardless I will be pushing 0.0.10 sometime today that will have all changes made since the last release on top of the templating/slugify changes so hopefully you can simply: `pip install upgrade bandcamp-downloader` and your problems will go away.

**Comment by jonnyburnaway** [comment]
Thanks for this - I'll upgrade once it's been pushed.

**Comment by Evolution0** [comment]
@jonnyburnaway Give it a try now after updating.

**Comment by jonnyburnaway** [comment]
Thanks - fixed my issue!
