### ISSUE TITLE
Private albums no longer downloadable?

### ISSUE THREAD

**Issue by aspain** [Evolution0/bandcamp-dl#181]
**Describe the bug**
Some albums show a full track listing for an album, but only particular songs have the 'play' button next to them, allowing you to listen to them. So, the songs that you cannot preview or listen to without purchase, are considered 'private'. 

bandcamp-dl gives a `Track list incomplete, some tracks may be private, download anyway? (yes/no):`  prompt, to which you can reply 'yes', but it will still only download those songs which were 'previewable' on the bandcamp site. 

**To Reproduce**
Command to reproduce the behavior:
`bandcamp-dl https://goosetheband.bandcamp.com/album/ted-tapes-2021`
```
https://goosetheband.bandcamp.com/album/ted-tapes-2021
```

**Expected behavior**
I would expect bandcamp-dl to still be able to download the entire album, but it seems the 'private' setting for songs may block this

**Desktop (please complete the following information):**
 - OS: Mac
 - Version Catalina 10.15.7
 - Python Version 3.6.4

**Comment by Evolution0** [comment]
"but it will still only download those songs which were 'previewable' on the bandcamp site."

Expected behavior, the prompt may just be misleading, it does not mean it will download the private tracks but that it will simply continue and download what tracks it _can_.

Bandcamp-DL gets the tracks from the preview player itself, so if a track isn't previewed...
