### ISSUE TITLE
Feature to change location of download

### ISSUE THREAD

**Issue by BlastkinS** [Evolution0/bandcamp-dl#199]
This could either be a bug from my pc as it doesn't change the location of the downloaded mp3's and stays with C:\Users\--\ and not wherever i set the cd command to

I would like to be able to download albums and releases under other locations than the basic cmd location.

**Comment by Evolution0** [comment]
Not a bug, its intended. Its setup this way so that you can just open a terminal anywhere and run it as a lot of people that use the utility aren't command line literate.

The method to change the location of where files are downloaded is explained either via built in help `-h, --help` or https://github.com/iheanyi/bandcamp-dl#options (See `--base-dir=`)

**Comment by dm2912** [comment]
is there way to permanently set this location in a config file as you can with youtube-dl for instance

**Comment by BlastkinS** [comment]
first of all --base-dir= is not anywhere in the help menu or the options menu of the bandcamp-dl github
and second i have to set --base-dir= everytime i gotta download music but thats alright i guess.

edit: also base-dir doesnt work for some reason
re-edit: yeah ok it does work but like i said i have to set it everytime i download something which is kinda annoying. otherwise, thanks for the help.

**Comment by guttitto** [comment]
I'd also like to change it permanently if possible
