### ISSUE TITLE
Speed throttling while downloading

### ISSUE THREAD

**Issue by Jeddunk** [Evolution0/bandcamp-dl#22]
I guess this won't be solveable, but I'll post it anyways. The download always begins at a very high speed (~ 3 Mbit/s) before being throttled to ~45 Kbit/s.

**Comment by iheanyi** [comment]
Hmmm, that's interesting. Maybe its getting throttled on the client-side by Bandcamp? ._.

**Comment by Jeddunk** [comment]
There might be a few ways to make this not as big of a problem than it is now:
- Limit the download speed reasonably (maybe ~200kbit/s?)
- Mask the downloader as a browser (http://www.useragentstring.com/)

Since I've no clue how Python works, I don't know how easy/hard it is to implement these. Even if there is a way to implement them, this problem may still happen regardless.

**Comment by omgiafs** [comment]
I think that first megabyte downloads so fast because of cache mechanism of Bandcamp.
After first megabyte speed throttled hard to ~50 KiB/sec, it's enough to play mp3 in best quality.

So, if you want to download many albums as faster as you can, you just need to start download to multiple streams. I've made it with batch script :)

**Comment by Bendito999** [comment]
This seems to be fixed on the newest release. I would vote to close.

**Comment by Evolution0** [comment]
Doesn't seem to be an issue anymore.
