### ISSUE TITLE
Can't update via pamac on Manjaro Linux

### ISSUE THREAD

**Issue by Ego-X** [Evolution0/bandcamp-dl#225]
Update to Arch via AUR cancels with an error.

The update is carried out via Pamac

According to the log, the setup.py is missing

Erstelle bandcamp-dl-git...
==> Erstelle Paket: bandcamp-dl-git v0.0.13.r38.gd454199-1 (Do 04 Jul 2024 09:34:00 CEST)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Empfange Quellen...
  -> Aktualisiere das bandcamp-dl git Repo...
==> Überprüfe source Dateien mit sha512sums...
    bandcamp-dl ... Übersprungen
==> Entferne existierendes $srcdir/ Verzeichnis...
==> Entpacke Quellen...
  -> Erstelle Arbeitskopie des bandcamp-dl git Repos...
Klone nach 'bandcamp-dl'...
Fertig.
==> Beginne pkgver()...
==> Entferne existierendes $pkgdir/ Verzeichnis...
==> Betrete fakeroot Umgebung...
==> Beginne package()...
python: can't open file '/var/tmp/pamac-build-martin/bandcamp-dl-git/src/bandcamp-dl/setup.py': [Errno 2] No such file or directory
==> FEHLER: Ein Fehler geschah in package().
    Breche ab..
``

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Version 24.0.2
 - Python Version 3.12.4

**Comment by Evolution0** [comment]
I have no control of the package in the AUR, we no longer use a `setup.py` and build and install using the `pyproject.toml` exclusively.

The build script on the AUR needs to be adjusted to pull in the `build` package from Pypi then to run `python -m build && pip install .`

As a matter of fact all alternative methods of installation that use custom build scripts like the AUR and Brew are likely broken until they have been updated by their respective maintainers.

**Comment by jneidel** [comment]
AUR package maintainer here.

I already switched the package to the equivalent of `python -m build && pip install .`:
```
  python -m build --wheel --no-isolation
  python -m installer --destdir="$pkgdir" dist/*.whl
```
[see](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=bandcamp-dl-git&id=9ce1ca5902fc9483d87a0f30c088f07da7e7c7db)

Clean build installs fine.

@Ego-X you seem to have a weird mixup of latest version, but outdated build & package commands.
If you post the PKGBUILD file you are trying to install I can check it.
Next time please point packaging issues directly to the maintainer by writing a comment here: https://aur.archlinux.org/packages/bandcamp-dl-git or emailing them directly. Your issue is not related to the project.

**Comment by Evolution0** [comment]
No response and fixed by AUR package maintainer, closing.
