### ISSUE TITLE
Cloning the repo is an 85mb download!

### ISSUE THREAD

**Issue by simonwjackson** [Evolution0/bandcamp-dl#29]
![screenshot from 2015-07-15 19-34-28](https://cloud.githubusercontent.com/assets/189379/8705212/8a3cd434-2b28-11e5-9ee8-2ca430c4e769.png)

Did someone accidentally commit a couple of MP3s to the repo? :)

**Comment by iheanyi** [comment]
Oi, good catch. Let me investigate this later. Thanks!

**Comment by tophertimzen** [comment]
Yeah, something is going on. There is a 88mb pack file in the repo. "pack-8441a5ea089a34e33d5edbae8bb0173c2b9a26b3.pack"

Looks like it is full of .mp3 files caused from the initial commit!

**Comment by kapitanluffy** [comment]
Initialized a new repository. You can check it out [here](https://github.com/kapitanluffy/bandcamp-dl)

https://github.com/kapitanluffy/bandcamp-dl

**Comment by tophertimzen** [comment]
It would be possible to just erase the .mp3 files in this repository commit history instead of making a new repo without the previous commit history.

**Comment by iheanyi** [comment]
Yeah, I was planning on removing those MP3 files. It makes me angry that
people just re-upload rather than just forking and implementing a pull
request, I'll fix this tomorrow morning.

**Comment by tophertimzen** [comment]
Yeah understandably. Doing that goes against the whole nature of GitHub.

**Comment by kapitanluffy** [comment]
Oh, I initially planned forking/removing but I don't know how I can remove the said mp3 files from the repo. I tried downloading forks of the project but it still has more than 80mb

**Comment by ali** [comment]
@kapitanluffy I don't think removing the repo history is the correct solution.

**Comment by ali** [comment]
Decided to look into this, and I was able to slim down the repo to 43.25kb:

```
orchid% hub clone https://github.com/ali/bandcamp-dl                        
Cloning into 'bandcamp-dl'...
remote: Counting objects: 203, done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 203 (delta 1), reused 0 (delta 0), pack-reused 140
Receiving objects: 100% (203/203), 43.26 KiB | 0 bytes/s, done.
Resolving deltas: 100% (96/96), done.
Checking connectivity... done.
```

[I found a "files" directory](https://gist.github.com/ali/6cd2f3fa65d150904f28) in the repo history that had a bunch of mp3s in it, so I removed it and force-pushed the "slimmed" master branch to my fork: https://github.com/ali/bandcamp-dl.git

@iheanyi I don't think this is a change I can merge in because your repo still has the mp3s in its history. You can remove the files directory from the repo history yourself and force-push your master branch back upstream, but I'm not sure what implications this has for previously-created forks pushing their changes in.

To remove the "files" dir from every commit:  `git filter-branch --prune-empty --index-filter 'git rm -rf --cached --ignore-unmatch ./files' --tag-name-filter cat -- --all`

**Comment by tophertimzen** [comment]
@iheanyi you should follow what @ali did and clean the repo history for easier usability.

**Comment by iheanyi** [comment]
Yeah, gonna do that now. Thanks y'all.

**Comment by iheanyi** [comment]
Okay y'all, I've fixed this. @ali @tophertimzen and everybody, make sure you do a clean clone of the repo that has all of the messy files removed from it. Thanks!
