### ISSUE TITLE
Couldn't write lextab module <module 'slimit.lextab' from '/usr/local/lib/python2.7/dist-packages/slimit/lextab.pyc'>

### ISSUE THREAD

**Issue by rdlmda** [Evolution0/bandcamp-dl#34]
`WARNING: Couldn't write lextab module <module 'slimit.lextab' from '/usr/local/lib/python2.7/dist-packages/slimit/lextab.pyc'>. Won't overwrite existing lextab module.`

```
WARNING: yacc table file version is out of date
WARNING: Token 'IMPORT' defined, but not used
WARNING: Token 'BLOCK_COMMENT' defined, but not used
WARNING: Token 'ENUM' defined, but not used
WARNING: Token 'EXTENDS' defined, but not used
WARNING: Token 'LINE_COMMENT' defined, but not used
WARNING: Token 'LINE_TERMINATOR' defined, but not used
WARNING: Token 'CONST' defined, but not used
WARNING: Token 'EXPORT' defined, but not used
WARNING: Token 'CLASS' defined, but not used
WARNING: Token 'SUPER' defined, but not used
WARNING: There are 10 unused tokens
```

**Comment by rdlmda** [comment]
According to https://github.com/dabeaz/ply/issues/63 supposedly this is fixed on ply 3.7.
I have, however, installed ply 3.8 via pip and the issue persists.

**Comment by imampossible** [comment]
Yeah, I don't know what the deal is. I've done practically everything from un/reinstalling python as with the packages to use for this program. Used 2.7 and 3.X but still nothing. Tried uninstalling, deleting, and reinstalling things with ply. So far no dice, I'm still getting this same warning.

**Comment by JohnSelleck** [comment]
Same problem persist in my case too. As ruda-almeida stated, i tried reinstalling ply3.8 and replacing files, also tried the whole instalation proces from clean slate but problem persists. With me the problem is with these files: yacctab.pyc and lextab.pyc.
Tried and searched for solution but still didn't find one. 

Edit:
 I tried installing Ply3.4 and the warning is gone but now the problem remains:

uknown url type: //popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=0bf275fcbe374c0d12eb8ff9af6ed62&id=2945142706&stream=1&ts=1445767726.0
Downloading failed...

**Comment by JohnSelleck** [comment]
Found a solution:
1. You need Ply 3.4 installed instead of Ply 3.8.
2. In BandcampDownloader.py find line number 68 and repleace it with:
               tmp_file = wgetter.download(('http:')+(track['url']), outdir=dirname)
        Thanks to: JackRonan in https://github.com/iheanyi/bandcamp-dl/issues/32
Everything should now work perfectly.

**Comment by imampossible** [comment]
Can confirm that the solution works. Thank you John and Jack, you're a lifesaver [and a time saver!]

**Comment by scuml** [comment]
To summarize, run:

```
pip uninstall ply
pip install ply==3.4
```

**Comment by iheanyi** [comment]
Fixed by https://github.com/iheanyi/bandcamp-dl/commit/83554e891dd942b6d95c5ca379759376e98b259b, thanks for the report!
