### ISSUE TITLE
How to get faster download?

### ISSUE THREAD

**Issue by imampossible** [Evolution0/bandcamp-dl#38]
Maybe it might just be happening on my end but does anyone know how to get faster downloading speed with this program? What seems to be happening is that it starts out with my max internet speed which is around 1.5 - 2MBs per sec for a few seconds then gets capped down to 40KB and 55 KB per sec when it tries downloading each song. Is there a fix or workaround for this?

**Comment by Ristellise** [comment]
AFAIK I know it downloads firsts... then converts to mp3 /mp4

**Comment by imampossible** [comment]
I understand. That makes sense why it would do that.

**Comment by Bendito999** [comment]
Nope, it's on Bandcamp's end. The reasoning is that, when downloading the MP3 file to your machine, its only supposed to play in the webbrowser. Playing in real time requires a burst at the beginning to establish some buffer, but only requires a slow rate after that. (at worst case, a 5 minute song could take up to 5 minutes to download and no one would notice, because you are supposed to be listening to the song during that time). This saves Bandcamp bandwidth from people who might just listen to the first section of a song without listening to the whole thing; they didn't have to waste data sending over the entire song. It also provides minor hinderance to downloaders (though with proper automation, who cares if it takes all day, its unattended).

No real conversion takes place in this program; that would be silly converting from a lossy .mp3 to another .mp3. Better to just take the original 128k lossy mp3 and keep it, as it was encoded on Bandcamp's side from the original FLAC source. It's like why downloading youtube as mp3 is silly, why not just keep the original AAC encoded audiostream and simply repackage (not transcode) it into .m4a (which is as ubiquitous as the mp3). This can be done in youtube-dl (which is also conveniently a bandcamp downloader, just not as good of one).

**Comment by imampossible** [comment]
Glad to see it isn't my end, I should of known as I've used other [site-url-here] to mp3 converters before and they take a long time to get the file. Thank you for clearing that up.
