### ISSUE TITLE
Can't seem to run program

### ISSUE THREAD

**Issue by nuentes** [Evolution0/bandcamp-dl#47]
After a bit of struggling (mostly due to lxml), I've gotten this installed, but I'm still having trouble using it.  I might be running the commands incorrectly, but I've tried quite a few different things.  Any ideas?  Do I need to add another environment path variable?

`C:\Users\duboi>pip uninstall bandcamp-downloader
Uninstalling bandcamp-downloader-0.0.3:
  c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_dl__init__.py
  c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_dl__pycache____init__.cpython-35.pyc
  c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_dl__pycache__\bandcamp.cpython-35.pyc
  c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_dl\bandcamp.py
  c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_dl\bandcamp_dl.py
  c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_dl\bandcampdownloader.py
  c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_dl\jsobj.py
  c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_downloader-0.0.3.dist-info\description.rst
  c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_downloader-0.0.3.dist-info\entry_points.txt
  c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_downloader-0.0.3.dist-info\installer
  c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_downloader-0.0.3.dist-info\metadata
  c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_downloader-0.0.3.dist-info\metadata.json
  c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_downloader-0.0.3.dist-info\record
  c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_downloader-0.0.3.dist-info\top_level.txt
  c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_downloader-0.0.3.dist-info\wheel
  c:\users\duboi\appdata\local\programs\python\python35-32\scripts\bandcamp-dl.exe
Proceed (y/n)? y
  Successfully uninstalled bandcamp-downloader-0.0.3

C:\Users\duboi>pip install bandcamp-downloader
Collecting bandcamp-downloader
Requirement already satisfied (use --upgrade to upgrade): slugify==0.0.1 in c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages (from bandcamp-downloader)
Requirement already satisfied (use --upgrade to upgrade): mutagen>=1.31 in c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages (from bandcamp-downloader)
Requirement already satisfied (use --upgrade to upgrade): slimit>=0.8.1 in c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages (from bandcamp-downloader)
Requirement already satisfied (use --upgrade to upgrade): wgetter>=0.6 in c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages (from bandcamp-downloader)
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4>=4.4.1 in c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages (from bandcamp-downloader)
Requirement already satisfied (use --upgrade to upgrade): ply==3.4 in c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages (from bandcamp-downloader)
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.5.0 in c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages (from bandcamp-downloader)
Requirement already satisfied (use --upgrade to upgrade): docopt>=0.6.2 in c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages (from bandcamp-downloader)
Installing collected packages: bandcamp-downloader
Successfully installed bandcamp-downloader-0.0.3

C:\Users\duboi>bandcamp-dl.py (--help)
'bandcamp-dl.py' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\duboi>bandcamp-dl (--help)
Traceback (most recent call last):
  File "c:\users\duboi\appdata\local\programs\python\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\duboi\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\duboi\AppData\Local\Programs\Python\Python35-32\Scripts\bandcamp-dl.exe__main__.py", line 5, in <module>
  File "c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_dl\bandcamp_dl.py", line 59
    print "The url {} is not a valid bandcamp page.".format(url)
                                                   ^
SyntaxError: invalid syntax

C:\Users\duboi>bandcamp-dl --help
Traceback (most recent call last):
  File "c:\users\duboi\appdata\local\programs\python\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\duboi\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\duboi\AppData\Local\Programs\Python\Python35-32\Scripts\bandcamp-dl.exe__main__.py", line 5, in <module>
  File "c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_dl\bandcamp_dl.py", line 59
    print "The url {} is not a valid bandcamp page.".format(url)
                                                   ^
SyntaxError: invalid syntax

C:\Users\duboi>bandcamp-dl.py --help
'bandcamp-dl.py' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by nuentes** [comment]
same error when I try to just download.  As you can see above, I uninstalled, and then installed again.  No errors.

Python 3.5 on Windows 10

`C:\Users\duboi>bandcamp-dl http://picturesque.bandcamp.com/album/picturesque-ep
Traceback (most recent call last):
  File "c:\users\duboi\appdata\local\programs\python\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\duboi\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\duboi\AppData\Local\Programs\Python\Python35-32\Scripts\bandcamp-dl.exe\__main__.py", line 5, in <module>
  File "c:\users\duboi\appdata\local\programs\python\python35-32\lib\site-packages\bandcamp_dl\bandcamp_dl.py", line 59
    print "The url {} is not a valid bandcamp page.".format(url)
                                                   ^
SyntaxError: invalid syntax`

**Comment by snelltheta** [comment]
I get the same exact errors.
I'm also using Python 3.5, and had some issues regarding lxml, as well, on a W10 install.

UPDATE:
I was able to make bandcamp-dl work using Python 2.7. It didn't want to work initially, but after installing from the source using pip, rather than doing "pip install bandcamp-downloader", the dependency, "requests" was installed, and I got it going.

`C:\Users\Steve\Downloads>bandcamp-dl https://fooband.bandcamp.com/album/foobar
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\bandcamp-dl.exe__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\bandcamp_dl\bandcamp_dl.py", line 42, in <module>
    from Bandcamp import Bandcamp
  File "c:\python27\lib\site-packages\bandcamp_dl\Bandcamp.py", line 2, in <module>
    import requests
ImportError: No module named requests

C:\Users\Steve\Downloads>cd bandcamp-dl-master

C:\Users\Steve\Downloads\bandcamp-dl-master>cd bandcamp-dl-master

C:\Users\Steve\Downloads\bandcamp-dl-master\bandcamp-dl-master>README.md

C:\Users\Steve\Downloads\bandcamp-dl-master\bandcamp-dl-master>pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4==4.4.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): lxml==3.5.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): mutagen==1.31 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): ply==3.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Collecting requests==2.8.1 (from -r requirements.txt (line 6))
  Using cached requests-2.8.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): slimit==0.8.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): slugify==0.0.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): wgetter==0.6 in c:\python27\lib\site-packages (from -r requirements.txt (line 9))
Installing collected packages: requests
Successfully installed requests-2.8.1
C:\Users\Steve\Downloads\bandcamp-dl-master\bandcamp-dl-master>bandcamp-dl https://bandpagefoobar.bandcamp.com/album/foo
Starting download process.`

**Comment by berrythesoftwarecodeprogrammar** [comment]
yea you must clone the git repo. and if installing it with the included instructions doesnt work exactly then it wont end up working. for my python2.7 i had to install a `Microsoft Visual C++ Compiler for Python 2.7` and then my `pip install -r requirements.txt` finally worked

**Comment by iheanyi** [comment]
Ohhhhh snap. I definitely made this using Python 2.7 without checking for Python 3 compatibility...hmmm.

**Comment by nuentes** [comment]
Ok, I finally got around to installing this on my other PC.  After following the above instructions, I'm up and running.  It'd be nice to see this working with Python 3, though, as I don't want to have multiple installs of python.

**Comment by iheanyi** [comment]
@nuentes - Thanks for the feedback, I'll have to do further testing on Python 3 to add that compatibility and also, I didn't know that there were extra steps on Windows, as I'm on OS X. :/

**Comment by Evolution0** [comment]
Old Python 3 compatibility issue, closing.
