### ISSUE TITLE
Syntax issues

### ISSUE THREAD

**Issue by hippolyte-dubois** [Evolution0/bandcamp-dl#66]
Hmm.

I feel like an idiot right now.

I've been trying to understand the syntax, i'm used to bash and command-line python, i'm a big user of scdl, but i don't get this one.
Here's the command : 

> bandcamp-dl --full-album "https://rosswhyte.bandcamp.com/album/kaidan" --verbose

Here's the error output : 

> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.5/bin/bandcamp-dl", line 9, in <module>
>     load_entry_point('bandcamp-downloader==0.0.3', 'console_scripts', 'bandcamp-dl')()
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/**init**.py", line 542, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/**init**.py", line 2569, in load_entry_point
>     return ep.load()
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/**init**.py", line 2229, in load
>     return self.resolve()
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/**init**.py", line 2235, in resolve
>     module = **import**(self.module_name, fromlist=['**name**'], level=0)
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bandcamp_dl/bandcamp_dl.py", line 59
>     print "The url {} is not a valid bandcamp page.".format(url)
>                                                    ^
> SyntaxError: invalid syntax

**Comment by iheanyi** [comment]
@IgorDubois Try using Python 2.7, that's what this was coded with. :X Sorry for that.

**Comment by Evolution0** [comment]
[I've forked and modified it a bit so that it works.](https://github.com/Evolution0/bandcamp-dl) (In Python 3.5.2 at least)

In the process I also had to modify Slugify and include it as the author seems to have abandoned it.

deps.txt and requirements.txt have been modified appropriately, must be cloned and installed from source using the instructions as I'm not about to put it on pypi (Its your project) and I'm not comfortable making a PR for it to be merged yet.

I might make a PR after I:
Recode some stuff to use asyncio/aiohttp
Merge @Bendito999's changes
Write my own function to replace Slugify.
Improve default file naming e.g: `Foo - Bar (Ft. Baz).mp3` vs. `foo-bar-ft-baz.mp3`. `--template` would override.

No idea when I might do these things though, but hey at least it works in the mean time eh?

**Comment by iheanyi** [comment]
Yeah. I'm wondering if there's a way we can make this work with both Python 3 and Python 2? 🤔

**Comment by Evolution0** [comment]
I've kinda got it cross-compatible as-in it at least grabs the tracks and names them from a bc album/page link.

Currently not working:

Metadata
Album art
Progress bar (Broken in Python 2.7.11 _and_ 3.5.2)

If the progress bar is part of wgetter (I would assume so) I might end up replacing it anyway, as having wgetter _and_ requests is kind of redundant.

Possibly more. I'll mess around with it some more later :)

Edit: In case its not obvious I have not committed my most recent changes in my fork.

**Comment by iheanyi** [comment]
@Evolution0 I think the point of having `wgetter` was in order to have an easy way to download files to a specific output file more easily than you can do with Requests. Been awhile since I've worked on this script but that was my thought process around it.

**Comment by Evolution0** [comment]
Hm, currently it is:

```
tmp_file = wgetter.download(track_url, outdir=dirname)
os.rename(tmp_file, filename)
```

With requests:

```
r = requests.get(track_url, stream=True)
with open(dirname + "/" + filename, "wb") as file:
    file.write(r.content)
```

Not much harder and gets rid of a dep.

Edit: As a side effect of trying this out I noticed create_directory returns a strangely formed path (In my case):
`'D:\\bandcamp-dl\\bandcamp-dl\\bandcamp_dl/the-enigma-tng/asia-deth'`

Its mixing back and forward slashes because os.path isn't getting free reign to form the path itself. Its pretty smart, you can just set artist and album as folder names then join them to get the path.

I think maybe wgetter autocorrected the path?

**Comment by iheanyi** [comment]
@Evolution0 - Yeah, that may be the case. I honestly wasn't sure how WGetter was handling it, but it's a thin wrapper around `wget` so it probably does auto-correct the paths.

**Comment by Evolution0** [comment]
I found that the path formed by template_to_path was perfectly fine but when using requests to download the track I only needed the filename variable.

I removed what Python 2.7.X code I had for backwards compatibility while I sorted the dependency issue out.

I got everything working under Python 3.5.2 with the latest version of the deps, current dep list looks like this:
```
beautifulsoup4==4.5.1
docopt==0.6.2
lxml==3.6.4
mutagen==1.35.1
ply==3.9
requests==2.12.3
slimit==0.8.1
unicode-slugify==0.1.3
```

I added the progress bar back in without using a module so that is nice.

Now I just need to make it cross-compatible without making a mess of the code this time.
